### ISSUE TITLE
How to unsterstand the Pairwise Differences Analyses output 

### ISSUE THREAD

**Issue by zhang919** [hloefflerwirth/oposSOM#2]
Dear,
I recently read your article about oposSOM, thank you for your work, but I have some doubts about the output:
1) In the results of Pairwise Differences Analyses, I noticed the existence of some statistical tests, such as <t−score> and <p−value>. Can I think that the negative result of the statistical test here represents the two groups? There is no significant difference between and no comparison. Continue to analyze the heat map in the same file.
![图片](https://user-images.githubusercontent.com/16542149/89766958-92ba9700-db2b-11ea-9024-2e10dba0be47.png)
2) Another native problem is that I noticed that you mentioned in one of the earliest articles:
Does it mean that I should merge my biological replicates before analysis? 
Thanks for your attention.
Zhang

**Comment by hloefflerwirth** [comment]
1. The numbers of genes deceeding different fdr thresholds indicate if there are differentially expressed genes in the first place. Mean fdr, t and p values are averaged over the corresponding scores of all genes. Both should give a rough overview of the total degree of differential expression between the two groups.
2. Replicate merging usually depends on the total number of samples and replication. If you have 5 replicates control and 5 treatment, you should run oposSOM with all data available, without merging. If you have 1000 groups with 20 replicates each, you should think about merging.
In general: keep as much information in the training data as reasonable.
